#pragma config(Sensor, S1,     left_korma,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     right_korma,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     nose,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     gir,            sensorEV3_Gyro)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int g;
int t;
int giroo = SensorValue[gir];
int l_korma = SensorValue[left_korma];
int r_korma = SensorValue[right_korma];
int nose_z = SensorValue[nose];
task main()
{
	while(1)
	{
		giroo = SensorValue[gir];
		nose_z = SensorValue[nose];
		l_korma = SensorValue[left_korma];
		r_korma = SensorValue[right_korma];
		g = nose_z+r_korma;
		t =(nose_z)-r_korma;
		if(t>5)
		{
			motor[left]=100;
			motor[right]=-50;
		}
		else
		{
			if(t<-5)
			{
				motor[left]=-50;
				motor[right]=100;
			}
			else
			{
				motor[left]=50;
				motor[right]=50;
			}
		}
	}
}
