#pragma config(Sensor, S1,     right_korma,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     left_korma,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     nose,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int r_korma = SensorValue[left_korma];
int l_korma = SensorValue[right_korma];
int nose_z = SensorValue[nose];
task main()
{
	resetGyro()
	while(1)
	{
		l_korma = SensorValue[left_korma];
		r_korma = SensorValue[right_korma];
		int nose_z = SensorValue[nose];
		if(l_korma > 20)
		{
			motor[left]=30;
			motor[right]=-25;
		}
		else
		{
			if(l_korma < 20)
			{
				motor[left]=-25;
				motor[right]=30;
			}
			else
			{
			motor[left]=-100;
		  motor[right]=-100;
			}
		}
	}
}
