#pragma config(Sensor, S1,     left_korma,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     right_korma,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     nose,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     gir,            sensorEV3_Gyro)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int giroo = SensorValue[gir]
int l_korma = SensorValue[left_korma];
int r_korma = SensorValue[right_korma];
int nose_z = SensorValue[nose];
task main()
{
	while(1)
	{
		giroo = SensorValue[gir]
		nose_z = SensorValue[nose];
		l_korma = SensorValue[left_korma];
		r_korma = SensorValue[right_korma];

		if(giroo<285)
		{
			if(nose_z>50)
			{
				if(l_korma>15)
				{
					motor[left]=30;
					motor[right]=15;
				}
				else
				{
					if(l_korma<15)
					{
						motor[left]=15;
						motor[right]=30;
					}
				}
			}
			else
			{
				motor[left]=-15;
				motor[right]=30;
			}
		}
		else
		{
				motor[left]=30;
				motor[right]=30;
		}
	}
}
