#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     port_giro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          port_rodar,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mot_rght,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


const int len_arr = 10;
int Arr[len_arr];
int Arr_frisen[len_arr]

void maseiwe_s_datcika()
{
	int ih = 0 ;
	while(ih<len_arr)
	{
   	    Arr[ih]=SensorValue(port_nose);
		ih++;
		sleep(100);
	}
}
void cp_arr()
{
 while(ih<len_arr)
	{
     Arr_frisen[ih]=arr[ih];
     ih++;
	}	
}
task main()
{
maseiwe_s_datcika();







}
