#pragma config(Sensor, S1, port_nose, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2, port_left, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, port_right, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4, port_gyro, sensorEV3_Gyro)
#pragma config(Motor, motorA, mot_left, tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor, motorB, port_radar, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, port_rul, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorD, mot_right, tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable
int rul;  // tekuschij ugol rulua   global
const int SPEED_RUL=30;

int distans_ot_robota_do_borta=25;
int v_max=40;
int gyro_real;

#include "filter_lib.c"


	void povorot(int ugol_povorota, int v_max)
	{
        while( ugol_povorota != SensorValue(port_gyro))
        {
        int Error_ygol = ugol_povorota - SensorValue(port_gyro);
        motor[mot_left]=5*Error_ygol;
        motor[mot_right]=-5*Error_ygol;


        }//while( ugol_povorota != SensorValue(port_gyro))
	}//povorot(new_kurs)


	void set_ugol_rul(int ff)
	{
		int f=ff;
		if(f > 60){ f=60;}
		if(f < -60){ f=-60;}

		setMotorTarget(port_rul, f, SPEED_RUL);
		waitUntilMotorStop(port_rul);

		rul=getMotorEncoder(port_rul);
	}

    void moveProporcional(int GiroscopTarget, int koef_usilenia , int v_max)
    {
        int GiroscopYgolOnline = SensorValue(port_gyro);
        int Error_ygol = GiroscopTarget - GiroscopYgolOnline;
        motor[mot_left]=v_max+Error_ygol*koef_usilenia;
        motor[mot_right]=v_max-Error_ygol*koef_usilenia;
    }//void moveProporcional(int GiroscopTarget, int koef_usilenia)






	task monnitor()
	{
		while(1)
		{
		sleep(1000)
		displayBigTextLine(12, "%d", SensorValue(port_gyro));
		}// while(1)
	}//task monnitor()




#include "init_lib.c"

task main()
{
	init_radar();
	sleep(300);

	init_rul();
	sleep(300);

	init_gyro();
	sleep(300);

	startTask(sensors);
	sleep(1000);

	startTask(filtr);
	sleep(1000);
	startTask(monnitor);

	playTone(600,100);

    sleep(1000)

    waitForButtonPress();
	playTone(600,100);

	StopTask(monnitor)

	int GiroscopTargetFrozen = 0
	int GiroscopTargetDinamik = 0

    while(1)
	{
		if(25<filtr_itog_nose)
		{
			int delta_distans_right =  distans_ot_robota_do_borta - filtr_itog_right;
			GiroscopTargetDinamik = GiroscopTargetFrozen - delta_distans_right;
			if(abs(delta_distans_right)<10)
			{	moveProporcional( GiroscopTargetDinamik, 1 , v_max);	}
			else
			{
				if(GiroscopTargetFrozen-GiroscopTargetDinamik>0)
				{	moveProporcional( GiroscopTargetFrozen-15, 1 , v_max);	}
				else
				{	moveProporcional( GiroscopTargetFrozen+15, 1 , v_max);	}
			}//if(abs(delta_distans_right)<10)
		}//if(70<filtr_itog_nose)
    povorot(-90, 50)
	}// while(1)
}// task_main;
