#pragma config(Sensor, S1, port_nose, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2, port_left, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, port_right, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4, port_gyro, sensorEV3_Gyro)
#pragma config(Motor, motorA, mot_left, tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor, motorB, port_radar, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, port_rul, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorD, mot_right, tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "init_lib.c"
#include "filter_lib.c"



const int v_max=60;



const int distans_ot_robota_do_borta=20;

const int K_usil_rula = 3 ;

const int LIMIT_delta = 35 ;



//voids


void moveProporcionalrul (int GiroscopTarget,  int v_max)
{  // dvigenie s upravleniem rulen proporcionalno otklonenia ot kursa po giroskopu
	int GiroscopYgolOnline = SensorValue(port_gyro);
	int Error_ygol = GiroscopTarget - GiroscopYgolOnline;
	motor[mot_left]=v_max ;
	//+Error_ygol*koef_usilenia;
	motor[mot_right]=v_max ;
	//-Error_ygol*koef_usilenia;
	set_ugol_rul(Error_ygol*K_usil_rula) ;
}//void moveProporcionalRul(int GiroscopTarget, int koef_usilenia)



void EnMoveGir(int EnkoderTarget, int giroTagetXZ)
{  // dvigaemcya poka enkoder otschitavaet zadannij ugol povorota vala dvigatelya


	int GiroscopTargetFrozen = giroTagetXZ;
	int GiroscopTargetDinamik = giroTagetXZ;
	resetMotorEncoder(mot_left);
	resetMotorEncoder(mot_right);

	int et = EnkoderTarget * 2; //dly togo chtobi v cikle ne delit na 2
	int SrArifmetikEnkoder;
	do
	{
		SrArifmetikEnkoder = (getMotorEncoder(mot_left)+getMotorEncoder(mot_right)) ;

		int delta_distans_right =  distans_ot_robota_do_borta - filtr_itog_right;
		if( delta_distans_right > LIMIT_delta )
		{   delta_distans_right = LIMIT_delta;  }
		else
		{ if( delta_distans_right < -LIMIT_delta )
			{ delta_distans_right = -LIMIT_delta; }
		}

		GiroscopTargetDinamik = GiroscopTargetFrozen - delta_distans_right;
		moveProporcionalrul( GiroscopTargetDinamik,  v_max);

	} while( SrArifmetikEnkoder < et ) ;
}//EnMoveGir(int EnkoderTarget, int giroTagetXZ)



void povorot(int ugol_povorota, int v_max)
	{
		if(ugol_povorota<0)
		{
	    	while( ugol_povorota+5 != SensorValue(port_gyro))
	   		{
	   		   int Error_ygol = ugol_povorota - SensorValue(port_gyro);
	   		   motor[mot_left]=Error_ygol;
	   		   motor[mot_right]=-Error_ygol;
	   		}//while( ugol_povorota+5 != SensorValue(port_gyro))
		}//if(ugol_povorota<0)
		else
		{
			while( ugol_povorota-5 != SensorValue(port_gyro))
	   		{
	   		   int Error_ygol = ugol_povorota - SensorValue(port_gyro);
	   		   motor[mot_left]=Error_ygol;
	   		   motor[mot_right]=-Error_ygol;
	   		}//while( ugol_povorota-5 != SensorValue(port_gyro))
		}//else	if(ugol_povorota<0)
	}//povorot(new_kurs)

void moveProporcional(int GiroscopTarget, int koef_usilenia , int v_max)
	{  // upravlenie povorotami ranoj moshnostiyu na grebie vinti
	    int GiroscopYgolOnline = SensorValue(port_gyro);
	    int Error_ygol = GiroscopTarget - GiroscopYgolOnline;
	    motor[mot_left]=v_max+Error_ygol*koef_usilenia;
	    motor[mot_right]=v_max-Error_ygol*koef_usilenia;
	}//void moveProporcional(int GiroscopTarget, int koef_usilenia)

void moveKyrs(int giroTagetXZ, int stoop)
	{ // digenie po kursu s pomoschyu giroskopa vdol
	//   borta po pravomu datchku bez rula toko vintami
	// bez encodera do togo kak nosovoi datchik uvidit bort
		int GiroscopTargetFrozen = giroTagetXZ;
		int GiroscopTargetDinamik = giroTagetXZ;
		while(stoop<filtr_itog_nose)
		{
			int delta_distans_right =  distans_ot_robota_do_borta - filtr_itog_right;

			if( delta_distans_right > LIMIT_delta )
			{   delta_distans_right=LIMIT_delta;  }
			else
			{ if( delta_distans_right < -LIMIT_delta )
				{delta_distans_right = -LIMIT_delta; }
			}

			GiroscopTargetDinamik = GiroscopTargetFrozen - delta_distans_right;
			moveProporcional( GiroscopTargetDinamik, 1 , v_max);


		}// while(1)
	}//void moveKyrs()


task main()
{
	start_init_main();
	start_filter_main();


	EnMoveGir(6000, 0);
			playtone(400,10);

/*
	moveKyrs(0,80);
	playTone(600,10);

	povorot(-90, 70);
	playTone(800,10);

	moveKyrs(-90,80);
	playtone(600,10);

	povorot(-180, 70);

	EnMoveGir(7000, -180);

	moveKyrs(-180,80);

	povorot(-270, 70);

	EnMoveGir(1000, -270);
*/


	/////////////////
	dispEndTimer();
}//task_main
