#pragma config(Sensor, S1,     left_d,         sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     giro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     nose,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     right_d,        sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int r_korma;
int l_korma;
int nose_z;
int giroo;

int vmax=100;

int dist_bort=30;
int delta_bort=5;

int kurs = 0;
int delta_kurs=5;
int eror;

int x;
float kp = 0.8;
float kd = 5;
int veror = 0;
int eror0 =0;

void mv_kurs()
{
			giroo = SensorValue[giro];
			eror = kurs - giroo;

			while( abs(eror) > delta_kurs )
			{
				/////////////////////////////////////////////////////////////////////////////////////

				giroo = SensorValue[giro];
				eror = kurs - giroo;
				veror = eror - eror0;
				x = eror * kp + veror * kd;
				motor[left]=x;
				motor[right]=-x;


				eror0 = eror;
				//////////////////////////////////////////////////////////////////////////////////////
			} //while(abs(eror)>5)

}//mv_kurs

task main()
{
	playTone(500,10);
	//sleep(1000);

	resetGyro(giro); //
  giroo = SensorValue[giro];
	sleep(1000);
  playTone(500,10);

	sleep(5000);
	playTone(600,10);

	//waitForButtonPress();


	while(1)
	{
		r_korma = SensorValue[right_d];
//		l_korma = SensorValue[left_d];
		nose_z = SensorValue[nose];
		giroo = SensorValue[giro];


		if(giroo<kurs-5)
		{

			while(giroo<kurs-1)  //
			{
				nose_z = SensorValue[nose];
				if(nose_z<40)
				{
					break;
				}
				giroo = SensorValue[giro];
				motor[left]=40;
				motor[right]=-15;

			}//while(giroo<kurs-1)


		} //if(giroo<kurs-5)
		else
		{
			if(giroo>kurs+5)
			{
				while(giroo>kurs)
				{
					nose_z = SensorValue[nose];
					if(nose_z<40)
					{
						break;
					}
					giroo = SensorValue[giro];
					motor[left]=-15;
					motor[right]=40;

				}//while(giroo>kurs)
			}//if(giroo>kurs+5)
			else
			{
				motor[left]=100;
				motor[right]=100;

			}//if(giroo>kurs+5)..else

		}// if(giroo<kurs-5) .. else

		if(r_korma>15)
		{
			if(r_korma<20)
			{
				motor[left]=100;
				motor[right]=100;
			}//if(r_korma<20)
			else
			{
				while(r_korma>20)
				{
					nose_z = SensorValue[nose];
					if(nose_z<40)
					{
						break;
					}
					if(giroo<kurs-30)
					{
						break;
					}
					else
					{
						giroo = SensorValue[giro];
						r_korma = SensorValue[right_d];
						motor[left]=100;
						motor[right]=90;
					}
				}//while(r_korma>20)
			}//if(r_korma<20)..else

		}
		else
		{
			while(r_korma<15)
			{
				nose_z = SensorValue[nose];
				if(nose_z<40)
				{
					break;
				}
				r_korma = SensorValue[right_d];
				motor[left]=90;
				motor[right]=100;
			}  //while(r_korma<15)
		}


		if(nose_z<30)
		{
			kurs = kurs-90;
			playTone(600,10);


			mv_kurs();
		}//if(nose_z<30)


		/*		if(kurs == -270)
		{
		while(1)
		{
		motor[left]=45;
		motor[right]=45;
		}
		}                       */

	}
} //  task main()
