#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     port_left,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     port_right,     sensorEV3_IRSensor)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable

#define dlog 1;

//int rul;  // tekuschij ugol rulua   global
int distans_ot_robota_do_borta=40;
const int v_max=100;


//include

#include "lib/sensor3_lib.c"
#include "lib/init_lib.c";
#include "lib/move_lib.c";
#include "lib/lib_turn.c";
#include "lib/lib_mvGyroRightToLeftBui.c";

task main()
{
	start_init_main();
	//--------------------------------------------

	int n=0;
	while(1)
	{
	mvGyroRightToLeftBui(n-5, 50); 	/*(int giroTagetXZ, int LeftBui)*/			playTone(600,10);
	mvGyroRightToEncoder(50, n-5);   /*(int EnkoderTarget, int giroTagetXZ)*/	playTone(600,10);

	n = n - 90;

	turn(n-15 , 100);					/*(int new_kurs, int v_max)*/				 playTone(600,10);

}

	////////////////   END
	dispEndTimer();

	}
