#pragma config(Sensor, S1, port_nose, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2, port_left, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, port_right, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4, port_gyro, sensorEV3_Gyro)
#pragma config(Motor, motorA, mot_left, tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor, motorB, port_radar, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, port_rul, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorD, mot_right, tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable

//int rul;  // tekuschij ugol rulua   global
int distans_ot_robota_do_borta=25;
const int v_max=100;



//include
#include "lib/init_lib.c";
#include "lib/move_lib.c";
//#include "lib/lib_turn.c";
#include "lib/lib_mvGyroRightToLeftBui.c"
//#include "lib/lib_mvGyroToEncoder.c";
#include "lib/lib_TurnAnRadius.c"


task main()
{
	start_init_main();
	//--------------------------------------------
int k_encoder=1000/66;
int enk = 0;

set_ugol_radar(-20);

int dist_1bui = SensorValue(port_nose);
if (dist_1bui > 60)
{
 enk=(dist_1bui-40) * k_encoder    // encoder otkluchat pered buem
 mvGyroRightToEncoder(enk , 0);	  /*(int EnkoderTarget, int giroTagetXZ)*/playTone(600,10);
}
	mvGyroRightToLeftBui(0, 40); 	/*(int giroTagetXZ, int LeftBui)*/		 playTone(600,10);
	mvGyroRightToEncoder(750, 0);	  /*(int EnkoderTarget, int giroTagetXZ)*/	 playTone(600,10);

int dist_2bui = SensorValue(port_nose);
if (dist_2bui > 60){
	enk = (dist_1bui-40) * k_encoder;
mvGyroRightToEncoder(enk, 0);	  /*(int EnkoderTarget, int giroTagetXZ)*/playTone(600,10);
}

	TurnAnRadius(-90, 100, -150);	/*(int v_left, int v_right, int giroTagetXZ)*/playTone(600,10);

if (dist_2bui > 60){
	enk = (dist_1bui-40) * k_encoder;
	mvGyroRightToEncoder(enk, -180);	  /*(int EnkoderTarget, int giroTagetXZ)*/	 playTone(600,10);
}
	mvGyroRightToLeftBui(-180, 40); 	/*(int giroTagetXZ, int LeftBui)*/		 playTone(600,10);

	TurnAnRadius(-90, 100, -320);	/*(int v_left, int v_right, int giroTagetXZ)*/playTone(600,10);
if (dist_2bui > 60){
	enk = (dist_1bui-40) * k_encoder;
	mvGyroRightToEncoder(enk, -360);	  /*(int EnkoderTarget, int giroTagetXZ)*/	 playTone(600,10);
}

	mvGyroRightToLeftBui(-360, 40); 	/*(int giroTagetXZ, int LeftBui)*/		 playTone(600,10);

	TurnAnRadius(-80, 100, -530);	/*(int v_left, int v_right, int giroTagetXZ)*/playTone(600,10);

mvGyroRightToEncoder(( (dist_1bui + dist_2bui )*k_encoder + 750), -540);	  /*(int EnkoderTarget, int giroTagetXZ)*/playTone(600,10);

	mvGyroRightToNose(-540,30);		  /*(int giroTagetXZ, int stoop)*/			 playTone(600,10);

	////////////////   END
	dispEndTimer();

	}
