#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic, modeEV3Ultrasonic_Listen)
#pragma config(Sensor, S2,     port_left,      sensorEV3_Ultrasonic, modeEV3Ultrasonic_Listen)
#pragma config(Sensor, S3,     port_right,     sensorEV3_Ultrasonic, modeEV3Ultrasonic_Listen)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int a;
int b;
int c;


task main()
{
	setSensorMode(port_nose, modeEV3Ultrasonic_Listen);
	setSensorMode(port_left, modeEV3Ultrasonic_Listen);
	setSensorMode(port_right, modeEV3Ultrasonic_Listen);
datalogClear();
//datalogFlash();
playTone(600,50);
sleep(1000);


time1[0]=0;
int ii=100;
while ( ii-- >1 )
{

int t1=time1[0];
	setSensorMode(port_right, modeEV3Ultrasonic_SI_Cm);
int t2=time1[0];
int dt=t2-t1;
sleep(250);
a=0;
 while ( a==0){
   sleep(25);
	 a=SensorValue(port_right);
}
int t3=time1[0]; int dt3=t3-t2;
	//datalogAddValueWithTimeStamp(0,time1[0]);

int t4=time1[0];
	setSensorMode(port_right, modeEV3Ultrasonic_Listen);
int t5=time1[0]; int dt5=t5-t4;
	sleep(200);


	/*
	setSensorMode(port_left, modeEV3Ultrasonic_Cm);
	  	b=SensorValue(port_left);

	setSensorMode(port_left, modeEV3Ultrasonic_Listen);


	setSensorMode(port_right, modeEV3Ultrasonic_Cm);
	  	c=SensorValue(port_right);
	setSensorMode(port_right, modeEV3Ultrasonic_Listen);
*/
		datalogDataGroupStart();

			datalogAddValue(0,time1[0]);

			datalogAddValue(1,a);
			datalogAddValue(2,dt);
			datalogAddValue(3,dt3);
			datalogAddValue(4,dt5);
	datalogDataGroupEnd();


}// while
playTone(1000,50);
sleep(1000);
}
