#pragma config(Sensor, S1, port_nose, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2, port_left, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, port_right, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4, port_gyro, sensorEV3_Gyro)
#pragma config(Motor, motorA, mot_left, tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor, motorB, port_radar, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, port_rul, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorD, mot_right, tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable

//int rul;  // tekuschij ugol rulua   global
int distans_ot_robota_do_borta=30;
const int v_max=1000;
//int gyro_real;

//include
#include "lib/init_lib.c"
#include "lib/move_lib.c"





task main()
{
	start_init_main();

  distans_ot_robota_do_borta=30;

	EnMoveGir(6000, 0);

  distans_ot_robota_do_borta=30;

	playTone(600,10);

	moveKyrs(0,70);

	playTone(600,10);

	turn(-80, 100);

	playTone(600,10);

	EnMoveGir(500, -90);

	playTone(600,10);

	moveKyrs(-90,70);

	playTone(600,10);

	turn(-170, 100);

	playTone(600,10);

	EnMoveGir(5000, -180);

	playTone(600,70);

	moveKyrs(-180,40);

	////////////////   END
	dispEndTimer();

	}
