#pragma config(Sensor, S1,     left_korma,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     right_korma,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     nose,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     gir,            sensorEV3_Gyro)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int g;
int t;
int giroo = SensorValue[gir];
int l_korma = SensorValue[left_korma];
int r_korma = SensorValue[right_korma];
int nose_z = SensorValue[nose];
task main()
{
	resetGyro(gir);
	motor[left]=100;
	motor[right]=33;
	sleep(14000);

	playTone(400, 5);
	sleep(500)

	motor[left]=0;
	motor[right]=0;
	sleep(1000);


	while(giroo>-90)
	{
		giroo=SensorValue[gir]
		motor[right]=100
		motor[right]=-100
	}

	playTone(400, 500);
	sleep(500)
}
