#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     port_left,      sensorEV3_IRSensor)
#pragma config(Sensor, S3,     port_right,     sensorEV3_IRSensor)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable

//int rul;  // tekuschij ugol rulua   global
int distans_ot_robota_do_borta=30; //70=40cm 60 = 35cm 55=30cm 40=20cm
const int v_max=100;

//include
#include "lib/sensor3_lib.c";
#include "lib/init_lib.c";
#include "lib/move_lib.c";
#include "lib/lib_turn.c";
#include "lib/lib_mvGyroRightToLeftBui.c";
#include "lib/lib_TurnAnRadius.c";

task main()
{
	start_init_main();
	//--------------------------------------------

	mvGyroRightToEncoder(600, 0);   /*(int EnkoderTarget, int giroTagetXZ)*/	playTone(600,10);
	mvGyroRightToLeftBui(0, 80); 	/*(int giroTagetXZ, int LeftBui)*/			playTone(600,10);

	turn(-60, 100);					/*(int new_kurs, int v_max)*/				 playTone(600,10);
	turn(-120, 100);				/*(int new_kurs, int v_max)*/				 playTone(600,10);
	turn(-170, 100);				/*(int new_kurs, int v_max)*/				 playTone(600,10);

	mvGyroRightToNose(-180,30);	/*(int giroTagetXZ, int stoop)*/			playTone(600,10);


	////////////////   END
	dispEndTimer();

	}
