#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     port_left,      sensorEV3_IRSensor)
#pragma config(Sensor, S3,     port_right,     sensorEV3_IRSensor)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define dlog 1;
//preprocessor dla datalog

string logname = "../rc-data/n0v2_%d";
string llog;


//const short llen = 1650;
 //   static short arr_stamp[llen];
//    ubyte ih = 0;  // indek poslednego izmerenia v massive
//    ubyte arr_code[llen];
//    short arr_value[llen];
// 	int arr_time[llen];

//string name="test.csv";
//ubyte len_name;
//int distans_ot_robota_do_borta=40;
//const int v_max=100;


task main()
{
	//resetAllSensorAutoID();
ubyte ii=0;
stringFormat(llog,logname,ii);
while(bEv3FileExists(llog))
	{
		ii++;
		stringFormat(llog,logname,ii);

  }

char data1 = ',';
char * pData = "test writing test programmi logov v file big new file";
float data2 = 314.2;
long data3 = 5000000;
short data4 = 3200;

string sst = "test programmi logov v file big new file";
 	//len_name = sizeof(sst);
	eraseDisplay();
	displayBigTextLine(1, "LL = %d ", ii);

int id = fileOpenWrite(llog);
fileWriteChar(id, data1);

fileWriteData(id, pData, 35);
fileWriteChar(id, data1);


fileWriteFloat(id, data2);
fileWriteChar(id, data1);


fileWriteLong(id, data3);
fileWriteChar(id, data1);

//fileWriteData(id, data3,1);


fileWriteChar(id, data1);


fileWriteShort(id, data4);
fileWriteChar(id, data1);


fileClose(id);
sleep(15000);
////////////////   END
//dispEndTimer();
}
