#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     port_left,      sensorEV3_IRSensor)
#pragma config(Sensor, S3,     port_right,     sensorEV3_IRSensor)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define dlog 1;
//preprocessor dla datalog


int idr, id, idtmp;


task main()
{

string  logtemplate = "n0v2_%d.csv";
string  llog;
//= "                                                              ";
time1[0]=0;
ubyte ii=0;

do  // fomiruem filename
{
	stringFormat(llog,logtemplate,ii);
    ii++;
    idr =  fileOpenRead(llog);
    idtmp =idr;
    if ( idr>0 )
	    { fileClose(idr); }
}while (idtmp>0);

//char data1 = ',';
//char comma = ',';
char LF = '\n';
//char * pData = "test writing test programmi logov v file big new file";
float data2 = 314.2;
long data3 = 5000000;
//short data4 = 3200;

//string sst = "test programmi logov v file big new file";


id = fileOpenWrite(llog);
char * ts= "                    ";


for (short nn=0; nn<1000; nn++)
{

	sprintf(ts,  "nn=% 3d, ",  nn);
	fileWriteData(id, ts,8);
//wait1Msec(10);
 //ts= "                    ";
	sprintf(ts,"stamp=% 6d ,",  time1[0]);
	fileWriteData(id, ts, 14);
//wait1Msec(10);
//  ts= "                    ";
	sprintf(ts, " %4.1f ," ,  data2 );
	fileWriteData(id, ts, 8);
//wait1Msec(10);
//  ts= "                    ";
	sprintf(ts, "% 7d ," ,  data3 );
	fileWriteData(id, ts, 10);
//wait1Msec(10);


fileWriteChar(id, LF);
//wait1Msec(10);
sleep(10);


}

	//len_name = sizeof(sst);
	eraseDisplay();
	displayBigTextLine(1," nfile= % 3d ", ii);


fileClose(id);
sleep(5000);
////////////////   END
//dispEndTimer();
}
