#pragma config(Sensor, S1,     port_nose,      sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     port_left,      sensorEV3_IRSensor)
#pragma config(Sensor, S3,     port_right,     sensorEV3_IRSensor)
#pragma config(Sensor, S4,     port_gyro,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          mot_left,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          port_radar,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          port_rul,      tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          mot_right,     tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define dlog 1;
//preprocessor dla datalog


int idr, id, idtmp;
char  tss[5908];
char * ts = "";

task main()
{

<<<<<<< HEAD
do  // formiruem new filename
{
	stringFormat(llog,logtemplate,ii);
    ii++;
    idr =  fileOpenRead(llog);
    idtmp =idr;
    if ( idr>0 )
	    { fileClose(idr); }
}while (idtmp>0);
=======
	string  logtemplate = "n0v2_%d.csv";
	string  llog;
	//= "                                                              ";
	time1[0]=0;
	ubyte ii=0;
>>>>>>> cdac26848dccb5b67c40dded11bc059362670b76

	do  // fomiruem filename
	{
		stringFormat(llog,logtemplate,ii);
		ii++;
		idr =  fileOpenRead(llog);
		idtmp =idr;
		if ( idr>0 )
		{ fileClose(idr); }
	}while (idtmp>0);


	ubyte lss=strlen(logtemplate);

	eraseDisplay();
	displayBigTextLine(1,"nfile= % 3d ", ii);
	displayBigTextLine(3,"strlen= % 3d ", lss);

	//char data1 = ',';
	char comma = ',';
	char LF = '\n';
	//char * pData = "test writing test programmi logov v file big new file";
	float data2 = 314.2;
	long data3 = 5000000;
	//short data4 = 3200;

	//string sst = "test programmi logov v file big new file";


	id = fileOpenWrite(llog);

	//"                         ";
	displayBigTextLine(5,"len ts= % 3d ", strlen(ts));


	for (short nn=0; nn<100; nn++)
	{

		sprintf(ts,  "% 4d",  nn);
		strcat(tss,ts);
		//fileWriteData(id, ts,4);
		//fileWriteChar(id, comma);

		//wait1Msec(10);
		//ts= "                    ";
		sprintf(ts,"% 7d",  time1[0] );
		strcat(tss,ts);
		//fileWriteData(id, ts, 7);
		//fileWriteChar(id, comma);

		//wait1Msec(10);
		//  ts= "                    ";
		sprintf(ts, "% 5.1f" ,  data2 );
		strcat(tss,ts);
		//fileWriteData(id, ts, 6);
		//fileWriteChar(id, comma);
		//wait1Msec(10);
		//  ts= "                    ";
		sprintf(ts, "% 8d" ,  data3 );
		strcat(tss,ts);
		//fileWriteData(id, ts, 8);
		//fileWriteChar(id, comma);
		//wait1Msec(10);

    //strcat(tss,'\n');
		//fileWriteChar(id, LF);
		//wait1Msec(10);
		//sleep(10);


	}

	//len_name = sizeof(sst);
short ff=strlen(tss);
displayBigTextLine(7,"l_tss= % 3d ", ff);
fileWriteData(id, tss, ff);


	fileClose(id);
	sleep(13000);
	////////////////   END
	//dispEndTimer();
}
